### ISSUE TITLE
Conflict with Source Han Fonts J

### ISSUE THREAD

**Issue by CarrotDLaw** [GuiWonder/SourceHanToClassic#1]
Currently this font family has the exact same name with Source Han Sans and Serif which causes conflicts during installation. Also, 'Source' is the reserved font name of Source Han Sans. 

Please consider giving this nice font a unique name!

**Comment by lxgw** [comment]
傳源黑體 / 传源黑体 / Chuanyuan Gothic

这个名称如何？

**Comment by CarrotDLaw** [comment]
傳源黑體 Inherited Spring Gothic
傳源明體 Inherited Spring Mincho

**Comment by GuiWonder** [comment]
非常感谢！暂时用了“尙古 Advocate Ancient”，后期考虑使用“傳源”，仍然提供原版名称，也可以自命名。

**Comment by UltimateAmitieKaiNiC** [comment]
由於日本隱藏字形的限制，大多數不是傳承字形，敬請諒解！

**Comment by GuiWonder** [comment]
日版的思源字型中，只有個別的字形未被使用（引用），因此透過讀取字型中的信息，幾乎所有的字形都能被找到。因此使用日版效果會最佳。

**Comment by UltimateAmitieKaiNiC** [comment]
只有「龍音暗意帝商」為短橫，其餘為豎點

**Comment by GuiWonder** [comment]
> 只有「龍音暗意帝商」為短橫，其餘為豎點

短橫的字形數目很少，有不少思源傳承化字型都放棄使用短橫，統一為豎點。如果想統一為豎點，將 uvs-get-jp1-MARK.txt 中帶有這幾個字的行刪除就可以了（或者在行首加上符號#）。
