### ISSUE TITLE
請提供尙古黑體HW及Variable

### ISSUE THREAD

**Issue by haydenwong7bm** [GuiWonder/SourceHanToClassic#12]
見[思源黑體下載頁](https://github.com/adobe-fonts/source-han-sans/tree/release)。

**Comment by GuiWonder** [comment]
黑體HW已添加至 [Releases](https://github.com/GuiWonder/SourceHanToClassic/releases/tag/1.006)，由於使用的工具 [otfcc](https://github.com/caryll/otfcc)  目前不適用 Variable，因此現在還無法提供 Variable 版本，感謝反饋。

**Comment by GuiWonder** [comment]
使用 [FontTools](https://github.com/fonttools/fonttools) 重寫代碼將 Variable 字體構建完成，僅包含[思源黑體](https://github.com/adobe-fonts/source-han-sans)或[思源宋體](https://github.com/adobe-fonts/source-han-serif) 2.0x 版內部的字圖，位於 [Releases](https://github.com/GuiWonder/SourceHanToClassic/releases) 中。
