### ISSUE TITLE
慤–𢡱及飠–𩙿未統一

### ISSUE THREAD

**Issue by haydenwong7bm** [GuiWonder/SourceHanToClassic#14]
<img width="650" alt="image" src="https://user-images.githubusercontent.com/51369959/193050268-8b7507d9-bf89-457b-83cf-edcd4ecc9b4e.png">
“慤” (U+6164) 應使用“𢡱” (U+22871) 字圖。
“飠” (U+98E0) 應使用“𩙿” (U+2967F) 字圖。

**Comment by GuiWonder** [comment]
已加入殻-殼, 飠-𩙿，由於 慤 只有楷化字圖，因此暫時沒有添加 慤–𢡱。
![BaiduShurufa_2022-9-30_20-15-53-2](https://user-images.githubusercontent.com/55447192/193268646-fbf89782-e4cf-412a-9557-7c3489a94c19.png)

**Comment by GuiWonder** [comment]
已加入殻-殼, 飠-𩙿，由於 𢡱 只有楷化字圖，因此暫時沒有添加 慤–𢡱。
![BaiduShurufa_2022-9-30_20-15-53-2](https://user-images.githubusercontent.com/55447192/193269137-63959e4e-a2fd-49f6-8675-597c2073784d.png)
