### ISSUE TITLE
”𱍐”（U+31350）可使用“示 + U+E0100”字圖

### ISSUE THREAD

**Issue by haydenwong7bm** [GuiWonder/SourceHanToClassic#17]
<img width="284" alt="image" src="https://user-images.githubusercontent.com/51369959/194704303-9a95cbd2-5c2e-4c11-8786-323d21d3c1b3.png">

**Comment by haydenwong7bm** [comment]
”䶹”（U+4DB9）可使用“屮 + U+E0101”字圖
<img width="418" alt="image" src="https://user-images.githubusercontent.com/51369959/194771285-d81c0dfe-af52-49b1-8558-43a48dde0ea7.png">

**Comment by GuiWonder** [comment]
已完成 𱍐䶹 的字圖，非常感謝！
