### ISSUE TITLE
“逞”应更换

### ISSUE THREAD

**Issue by Scratchbin** [GuiWonder/SourceHanToClassic#18]
所用字图中“呈”下作“壬”。需更换。
![image](https://user-images.githubusercontent.com/29145652/194720176-4769d908-0db7-48ed-806e-7580a56f26d3.png)

**Comment by GuiWonder** [comment]
思源黑体的字图有限，没找到更合适的。
![BaiduShurufa_2022-10-9_7-57-40](https://user-images.githubusercontent.com/55447192/194731688-ca30cdbd-6e4d-4f11-b6bf-f27ce248b0cd.png)

**Comment by Scratchbin** [comment]
噔噔咚

**Comment by GuiWonder** [comment]
在[秋空黑體](https://github.com/ChiuMing-Neko/ChiuKongGothic)CL中找到包括“逞”、“咚”在内的一些传承字形，[这是测试字体](https://github.com/GuiWonder/SourceHanToClassic/releases/tag/test-0002)。

**Comment by ChiuMing-Neko** [comment]
「逞」從「壬」或「王」亦是字鉛可以見到的字形，如不修改字形情況下維持康熙字典字頭從「王」字形就行。

**Comment by GuiWonder** [comment]
壬、王、丿+土，都很常见。
![呈](https://user-images.githubusercontent.com/55447192/199399645-c75ed4ed-0565-4275-9648-65dd068975cb.jpg)

**Comment by GuiWonder** [comment]
新版已使用[秋空󠄁黑體CL](https://github.com/ChiuMing-Neko/ChiuKongGothic)將部件統一，感謝[秋空󠄁黑體](https://github.com/ChiuMing-Neko/ChiuKongGothic)提供大量優質字圖。
