### ISSUE TITLE
试着用这个工具给可变字体转换了一下，结果崩坏了。

### ISSUE THREAD

**Issue by howlingFounts** [GuiWonder/SourceHanToClassic#2]
源文件是 [SourceHanSerif-VF.ttf](https://github.com/adobe-fonts/source-han-serif/raw/release/Variable/TTF/SourceHanSerif-VF.ttf)。
然后转换后崩坏了：
![image](https://user-images.githubusercontent.com/43498546/178407631-47f6dd84-aa22-4731-b26d-81cf78795aa2.png)

**Comment by GuiWonder** [comment]
测试了一下，不适用可变字体，感谢你的反馈。

**Comment by GuiWonder** [comment]
> 未来会支持可变字体版思源吗？

所用的字体处理引擎 [otfcc](https://github.com/caryll/otfcc) 对可变字体的支持不太好，后期版本可能会支持。

**Comment by GuiWonder** [comment]
使用 [FontTools](https://github.com/fonttools/fonttools) 重写代码将可变字体转换完成，仅包含[思源黑体](https://github.com/adobe-fonts/source-han-sans)或[思源宋体](https://github.com/adobe-fonts/source-han-serif) 2.0x 版内部的字图，位于 [Releases](https://github.com/GuiWonder/SourceHanToClassic/releases) 中。
