### ISSUE TITLE
隹部件未统一

### ISSUE THREAD

**Issue by ryanlo713** [GuiWonder/SourceHanToClassic#20]
如图
![image](https://user-images.githubusercontent.com/12672523/195990156-b23b5034-8988-408d-8c6d-6993121e6efa.png)

隔壁的字体
![image](https://user-images.githubusercontent.com/12672523/195990082-46dfdb95-b01d-4513-a001-ef753f1dfec4.png)

使用变体一的字如：
隹雀奞翟霍奪奮隺進罹羅隼焦隻隽瞿雁雄雅雇雉雊雌雎雒雕雛雝雞離難㲝䨄靃雙集蒦舊雚𦾔飌魋睢唯誰推惟脽錐淮椎萑維堆崔嵟碓陮帷㢈騅蜼鵻䳡濉雖鷕蓷嶊匯濰催摧皠鏙璀漼槯墔磪𣝤𪆐𣙇

使用变体二的字如：
巂䍜雔雥雦雈䧹猚隿雂雃雏雐雓雗雡雤䧱䧲䧴䧵䧷䧸䧻䧼䧾䧿䨁䨂䨃䨅䨆䨈䨉㸈䨇䨊䮶倠婎趡顀谁䧽踓锥琟焳㮅痽㕍醀䶆骓䱦蓶嶉䜃䗽维潍㜠嗺䜅慛膗凗熣繀獕㒑擓㨤

可能有缺漏，请见谅。

**Comment by GuiWonder** [comment]
感谢反馈！
本项目没有新造字，所有的字图都是思源字体内部的字图，思源字体的字图有限，因此无法做到所有部件统一。
另外有的字图在明体中有，在黑体中没有，比如“趡”，是因为思源黑体与思源宋体不统一造成的。
![BaiduShurufa_2022-10-16_10-35-27](https://user-images.githubusercontent.com/55447192/196015244-7608bfc8-084e-4f25-901f-dbde9ec7f116.png)
