### ISSUE TITLE
有没有可能解决一下替换系统字体时的下沉问题啊？

### ISSUE THREAD

**Issue by lonznt** [GuiWonder/SourceHanToClassic#22]

**Comment by lonznt** [comment]
![robbie20221025010048](https://user-images.githubusercontent.com/80406454/197583464-b8441819-48cf-4f58-83f6-422da0d5ea6d.jpg)
![robbie20221025010036](https://user-images.githubusercontent.com/80406454/197583470-7454a32d-2a56-45f8-b829-f59baf79da31.jpg)

就是这个样子，这种情况应该叫下沉吧？不是特别懂，看别人这么描述这种现象就学到了。
很喜欢这个字体，想替换来用。
谢谢。

**Comment by GuiWonder** [comment]
做了个[转换器](https://github.com/GuiWonder/MetrFont)，效果和GenSekiGothic差不多，[这是构建的字体](https://github.com/GuiWonder/MetrFont/releases/tag/test-AA-ttf)。
