### ISSUE TITLE
請問是否可以調整等寬字間距

### ISSUE THREAD

**Issue by MrLuke1110** [GuiWonder/SourceHanToClassic#23]
半型與全型文字的長度無法對齊

![image](https://user-images.githubusercontent.com/66194793/198450012-d23c2a49-06a1-4289-83f6-0efd9a733953.png)

**Comment by GuiWonder** [comment]
這個問題與思源黑體是一樣的。應該說思源黑體HW才是「等寬字體」，思源等寬的英文要寬一些，大約三個英文與兩個漢字同寬。

![BaiduShurufa_2022-10-28_11-12-12](https://user-images.githubusercontent.com/55447192/198493926-fcc8bed8-e1a0-4f57-bd81-1563e5923edf.png)

**Comment by MrLuke1110** [comment]
謝謝回覆，沒有發現是因為水平距離的關係導致對不齊，黑源等寬是真得有無法對齊的狀況；只是因為之前用到更紗黑體是可以對齊的，想說問看看…它應該就是用500/1000單位的關係

**Comment by GuiWonder** [comment]
嗯，像思源等寬這樣2/3寬的比較少見。
