### ISSUE TITLE
重要消息：秋空󠄁黑體增加了很多傳承字形

### ISSUE THREAD

**Issue by UltimateAmitieKaiNiC** [GuiWonder/SourceHanToClassic#24]
秋空󠄁黑體增加了很多傳承字形，要不要優化一下？
參照：https://github.com/ChiuMing-Neko/ChiuKongGothic/

**Comment by GuiWonder** [comment]
感谢提醒，试一下[这个测试版](https://github.com/GuiWonder/SourceHanToClassic/releases/tag/test-0002)如何？

**Comment by UltimateAmitieKaiNiC** [comment]
不错！

**Comment by GuiWonder** [comment]
新版已加入[秋空󠄁黑體CL](https://github.com/ChiuMing-Neko/ChiuKongGothic)字圖，感謝反饋！

**Comment by UltimateAmitieKaiNiC** [comment]
ありがとう！
