### ISSUE TITLE
希望serif也可以提供ttf版本

### ISSUE THREAD

**Issue by hingbong** [GuiWonder/SourceHanToClassic#25]
介于Windows有多数传统界面对otf支持性不佳，可以提供ttf版本，如果hinting制作困难，希望可以提供不带hinting的版本，感谢

**Comment by GuiWonder** [comment]
感谢建议！hinting的serif还做不了，[不带hinting的serif与hinting sans](https://github.com/GuiWonder/SourceHanToClassic/releases/tag/1.010-ttf) 已构建完毕。

**Comment by hingbong** [comment]
> 感谢建议！hinting的serif还做不了，[不带hinting的serif与hinting sans](https://github.com/GuiWonder/SourceHanToClassic/releases/tag/1.010-ttf) 已构建完毕。

感谢

**Comment by GuiWonder** [comment]
使用 Sans 方法对 Mono 和 Serif 做了 hinting 处理。Serif 可能存在一些问题，如果出现问题可使用 unhinted 版本。

**Comment by hingbong** [comment]
> 使用 Sans 方法对 Mono 和 Serif 做了 hinting 处理。Serif 可能存在一些问题，如果出现问题可使用 unhinted 版本。

玩着的一个差不多20年前的游戏，对 hinting 兼容不佳，已转用 unhinted 版本
