### ISSUE TITLE
“关”仍需改用 CN 字图

### ISSUE THREAD

**Issue by Scratchbin** [GuiWonder/SourceHanToClassic#27]
该问题貌似在引入秋空黑体 CL 字图后再次出现。结合简体情况（關 -> 関 -> 关）该字仍需要改用 CN 字图。

**Comment by GuiWonder** [comment]
“八+天”这个字图思源中没有，应该是第一次出现。如果视为合并字简化的话是没有问题的。旧字典对“八+天”的收录还是比较广的，查阅多部旧字典都有收录，有字典解释两种写法是同一字(“八+天"亦作“丷+天”)。况且[一点明体](https://github.com/ichitenfont/I.Ming)与[秋空󠄁黑體CL](https://github.com/ChiuMing-Neko/ChiuKongGothic)、微软正黑体、微软细明体、教育部标准宋体、全字库宋体、华康宋体等多款字体都采用“八+天”这种写法。我觉得这种写法更为美观，可以接受。
![BaiduShurufa_2022-11-30_21-6-46](https://user-images.githubusercontent.com/55447192/204936942-2bc7a28d-0f6b-491f-87cc-e4c3c352693d.png)
![BaiduShurufa_2022-11-30_20-48-51](https://user-images.githubusercontent.com/55447192/204936952-0479795d-f1ed-47c0-88bb-297e2018e1ef.png)

**Comment by Scratchbin** [comment]
美观是美观；但是最后一张图（话说那是《正字通》？）那个可能是指楷化字形或者那个字典自己搞错了。简体的“关”所取来源是“關”变形“関”（即 “𢇇” 变体），与从“灷”变来的类似“八天”形无关。见《传承字形部件检校表》之“关部件”，一点字坊对“关”形部件有所区分，另见一点明体“送”、“联”；即使对“笑”异体“咲”，一点字坊亦未从“八”形而是从点、撇；况且你在二楼所列的字体都是给繁体语境使用的，繁体语境又基本不常用“关”（U+5173）。

**Comment by GuiWonder** [comment]
其实这个字体的构建方法非常简单，“八天“字图来自[秋空󠄁黑體CL](https://github.com/ChiuMing-Neko/ChiuKongGothic)，如果不想使用这个字图，可修改[ChiuKongGothic-CL.json](https://github.com/GuiWonder/SourceHanToClassic/blob/main/main/ChiuKongGothic-CL.json)，删除“关”所在的行（第15行），然后在Actions中选择左侧的 Build all，运行Run workflow 就会构建和Releases一样的字体了。

**Comment by haydenwong7bm** [comment]
折衷方案：新增U+5173 U+E0102，顯示成CN字图

**Comment by GuiWonder** [comment]
> 折衷方案：新增U+5173 U+E0102，顯示成CN字图  

目前使用的方法還不能增加字圖。思源字圖數目已達到上限，增加字圖不太容易且易出錯，沒能成功。此方案就先放棄了。

**Comment by ChiuMing-Neko** [comment]
> 折衷方案：新增U+5173 U+E0102，顯示成CN字图 ![image](https://user-images.githubusercontent.com/51369959/216920346-3aae24c8-f769-4f5d-96e3-574ac8a7c0d9.png)

![圖片](https://user-images.githubusercontent.com/84143394/218104451-6e671ba1-36fe-4722-91bf-e4f573820d90.png)
不妥，從倒八的字圖安排到E0101更合適。

**Comment by haydenwong7bm** [comment]
我搞錯了😅
![image](https://user-images.githubusercontent.com/51369959/218106386-5429a9a8-f14a-4939-8c52-f82c9c983f5f.png)

**Comment by GuiWonder** [comment]
下一版嘗試把窄的(U+E0100)換成CN，改爲U+E0101，“八+天"字圖在舊字典中幾乎都收錄了，放棄感覺可惜。

![2023-2-10_21-56-46](https://user-images.githubusercontent.com/55447192/218109678-291de63f-1a72-4906-b2c4-107d2aebdfac.png)

**Comment by GuiWonder** [comment]
後綴為 SC 的使用 CN 倒八字圖，可通過異體選擇器選擇兩種字圖。  

![2023-2-11_17-18-8](https://user-images.githubusercontent.com/55447192/218250740-a3557394-dbf8-4090-a328-f53024a33ffe.png)

**Comment by GuiWonder** [comment]
已添加變體選擇器 U+5173 U+E0101 顯示成CN字图，其餘不變。
