### ISSUE TITLE
希望优化“的”字

### ISSUE THREAD

**Issue by ahdung** [GuiWonder/SourceHanToClassic#28]
“的”字感觉左小右大，不协调不饱满，希望像明兰那样。

![屏幕截图 2022-12-01 233455](https://user-images.githubusercontent.com/12094247/205094480-f229f9f7-c5ee-4c7e-9003-b3005c07909b.png)

**Comment by GuiWonder** [comment]
感谢反馈！本项目所有的字图都是[思源黑体](https://github.com/adobe-fonts/source-han-sans)和[秋空󠄁黑体](https://github.com/ChiuMing-Neko/ChiuKongGothic)内部的字图。鉴于本人对平面设计比较陌生，没有打算重绘新的字图（我绘制的字图可能很丑）。“的”字来源[思源黑体](https://github.com/adobe-fonts/source-han-sans)，如果感觉不合适可向[思源黑体](https://github.com/adobe-fonts/source-han-sans)反馈，非常抱歉。

**Comment by ahdung** [comment]
明白，这个字应该是秋空来的，感谢你的杰出付出。
