### ISSUE TITLE
`AdvocateAncientMonoJP-BoldIt.ttf`字体名缺少`Bold`，和`AdvocateAncientMonoJP-RegularIt.ttf`覆盖了

### ISSUE THREAD

**Issue by hingbong** [GuiWonder/SourceHanToClassic#29]
![image](https://user-images.githubusercontent.com/26398240/208135345-0c10622a-b5fa-4d2d-9358-8e5c0da6d6c8.png)
如同所示，缺少`Bold`

**Comment by GuiWonder** [comment]
错误已更正，感谢反馈！
