### ISSUE TITLE
“录”字未统一至“彔”

### ISSUE THREAD

**Issue by Scratchbin** [GuiWonder/SourceHanToClassic#3]
如题

**Comment by GuiWonder** [comment]
个人觉得“录”字用作“錄”的简化字情况较多，“錄”与“[彔](http://pic.guoxuemi.com/zhdzd/564.jpg)”的意思有些不同，统一的必要性不大。  
![5642](https://user-images.githubusercontent.com/55447192/182047603-df30bc36-9194-424a-a313-12693a7cd218.jpg)

**Comment by Scratchbin** [comment]
这个在我看来算合并字，毕竟大陆字形中繁体“彔”部件本身也作“录”。

**Comment by Scratchbin** [comment]
这个在我看来算合并字，毕竟大陆字形中繁体“彔”部件本身也作“录”。

**Comment by GuiWonder** [comment]
> 这个在我看来算合并字，毕竟大陆字形中繁体“彔”部件本身也作“录”。

好的，下一版统一“录”与“彔”。

**Comment by GuiWonder** [comment]
[新版](https://github.com/GuiWonder/SourceHanToClassic/releases/tag/20220801)已完成统一“录”与“彔”。

**Comment by GuiWonder** [comment]
已追加“禄渌氯椂睩”。
