### ISSUE TITLE
“風”部件的問題

### ISSUE THREAD

**Issue by Steve-Yuu** [GuiWonder/SourceHanToClassic#30]
如題，《檢校表》曰風的第三筆爲橫，而本字體卻寫作撇，望修正
另外部分部件存在違和感，此處不在一一説明
<img width="384" alt="image" src="https://user-images.githubusercontent.com/108906358/209898613-f6bca169-c547-4045-ac86-c1c1d1c52f1c.png">

<img width="662" alt="image" src="https://user-images.githubusercontent.com/108906358/209898654-1e41be51-13d1-4844-a345-7982b30aa0aa.png">

**Comment by GuiWonder** [comment]
感謝試用！本專案沒打算新造字圖或重繪字圖，所有的字圖都是[思源黑體](https://github.com/adobe-fonts/source-han-sans)和[秋空󠄁黑體](https://github.com/ChiuMing-Neko/ChiuKongGothic)內部的字圖。思源TC的風部件第三筆爲橫，而思源TC多爲楷化，因此選擇了第三筆爲平撇的字圖。風第三筆作撇在古籍中也非常常見，並非不可取。
![BaiduShurufa_2022-12-29_12-16-24](https://user-images.githubusercontent.com/55447192/209915414-7706701f-098d-4d25-b84c-bcd5a8509a13.png)
![feng_cr](https://user-images.githubusercontent.com/55447192/209916401-b5e219c2-2d12-45cb-a08e-7289fd5534a7.jpg)
