### ISSUE TITLE
大佬

### ISSUE THREAD

**Issue by 86380123** [GuiWonder/SourceHanToClassic#31]
请问下有没有交流群之类的，好渴望和作者交流呀

**Comment by GuiWonder** [comment]
很抱歉，什么都没有做。我个人不是专业的，懂的很少。我也没有加入过类似的交流群，如有不足和好的建议，还望您能指出来，谢谢！

**Comment by 86380123** [comment]
你好，现在就是您发布的工具，在弄“一简多繁”的时候，字体会严重缩小体积和字符数，这算不算一个bug呢？也可能是我想要弄的字体有一些字体特性？另外还想请教您一会关于可变字体的问题，就是一个字体有多个字重且字符和度量等等都一样，那么可以用弄个工具让两个字重或者多个字重进行插值，做成母版弄成可变字体吗？我用fc软件，基本所有官方多字重的都不能正常生成可变字体！

**Comment by GuiWonder** [comment]
这个项目在 1.010 版之前和 [TCFontCreator](https://github.com/GuiWonder/TCFontCreator) “一简多繁”使用的方法来自[《正确实现简转繁字体》](https://ayaka.shn.hk/s2tfont/)一文，这个方法需要使用伪字图作为简繁转换的词汇，而一个字体的字图数目是有限制的，所以需要从字体中删除一些生僻字的字图，文章中有说明。从 1.010 版开始和[华英明朝](https://github.com/GuiWonder/HuayingMincho)新版使用了另一种处理方法，不会改变字形数目。这两种方法各有优缺点，前一种方法的优点是，转换字典来源为 [OpenCC](https://github.com/BYVoid/OpenCC) 简单且丰富，可完成较复杂的转换；而后一种的转换字典是我个人收集的，相比之下词汇要少些，比如一些人名地名，且词汇中最多能处理两个“一简多繁”，比如“乾乾淨淨”、“發佈”。后一种的优点就是能保证字符数目，且在逻辑上优于前一种。
对于可变字体，不太清楚，很多地方都用不了。测试了一下[思源宋体](https://github.com/adobe-fonts/source-han-serif)VF的构建，构建中第一步生成了 SourceHanSerifVF-Heavy.otf 和 SourceHanSerifVF-ExtraLight.otf ，第二步用这两个 otf 生成可变字体。第一步的 otf 看上去比较特殊，在 Windows 下预览显示不太正常。附件是生成的文件。
![Shurufa_2023-1-2_11-33-53](https://user-images.githubusercontent.com/55447192/210193352-c9392be1-7992-4c93-aeeb-00549fd85a47.png)
[SourceHanSerifVF_1.zip](https://github.com/GuiWonder/SourceHanToClassic/files/10329938/SourceHanSerifVF_1.zip)
[SourceHanSerif-VF_2.zip](https://github.com/GuiWonder/SourceHanToClassic/files/10329939/SourceHanSerif-VF_2.zip)

**Comment by 86380123** [comment]
谢谢你的解答，还请你给一个可以及时的联系方式吧，这样回复式有点难以交流呢，谢谢

**Comment by GuiWonder** [comment]
> 谢谢你的解答，还请你给一个可以及时的联系方式吧，这样回复式有点难以交流呢，谢谢

交流群：493272883
