### ISSUE TITLE
希望在非地区性变体（即不带JP和SC后缀者）中调整单双引号的宽度

### ISSUE THREAD

**Issue by ryanlo713** [GuiWonder/SourceHanToClassic#32]
因为繁中环境里一般用直角引号，与英语混排会出现如图情况

![image](https://user-images.githubusercontent.com/12672523/213190501-e6f67cd0-c28f-4886-b5fe-761c9d90efb3.png)

JP版中更理想
![image](https://user-images.githubusercontent.com/12672523/213191288-290c14df-be33-4d1b-932b-92da8790bb30.png)

**Comment by GuiWonder** [comment]
好的，繁体(及非地区)标点将使用 JP 版的窄引号。可从 [Actions](https://github.com/GuiWonder/SourceHanToClassic/actions) 中下载字体，谢谢。
