### ISSUE TITLE
字型【夜】不统一

### ISSUE THREAD

**Issue by starcollect** [GuiWonder/SourceHanToClassic#33]
首先非常感谢大佬制作的尚古系列
个人也非常喜欢这一系列传承字型
在使用过程中发现一个情况，在尚古黑体/尚古等宽中的【夜】字是传承字型
但是在尚古明体中的【夜】字却貌似并没有修改
是遗漏了还是有什么别的考量？

**Comment by GuiWonder** [comment]
您好，本项目没有新造字图或重绘字图，所有字图都是思源和[秋空󠄁黑体](https://github.com/ChiuMing-Neko/ChiuKongGothic)内部的字图。黑体和等宽中的【夜】字来自[秋空󠄁黑体](https://github.com/ChiuMing-Neko/ChiuKongGothic)。目前秋空明朝体还没有发布，所以明体的字图还仅限于思源宋体内部的字图。此问题还需秋空󠄁明朝体发布之后再作处理，感谢您的反馈！

**Comment by starcollect** [comment]
了解 感谢大佬的回复~
