### ISSUE TITLE
部分字未統一

### ISSUE THREAD

**Issue by haydenwong7bm** [GuiWonder/SourceHanToClassic#34]
應統一：
丢 → 丟
俣 → 俁
呑 → 吞
吴 → 吳
娛 → 娱
并 → 幷
彙 → 彚
彞 → 彝
悮 → 悞
戬 → 戩
晩 → 晚
榝 → 樧
瀬 → 瀨
緑 → 綠
迖 → 达
郉 → 邢
頽 → 頹
濲 → 瀔
骩 → 骫（可用港版字圖，比台版字圖傳承）

![image](https://user-images.githubusercontent.com/51369959/216958690-f4ab5dc1-27de-4785-bfb4-8489ff5757a7.png)

另外「鈃」戶經切，一種長頸酒器，也跟「鉶」通，與讀經天切，用於人名「宋銒」的「銒」異，兩字不能合併。但「鈃」卻顯示爲「銒」。

**Comment by GuiWonder** [comment]
好的，感謝反饋！

**Comment by haydenwong7bm** [comment]
「骳」都可改用港版字圖。🙂

**Comment by GuiWonder** [comment]
好的。

**Comment by garfieldLSY** [comment]
……其實“丢”倒可以在CN用“丢”的字圖，銩右邊的“丢”也可以……第一筆打撇。

**Comment by haydenwong7bm** [comment]
> ……其實“丟”倒可以在CN用“丟”的字圖，銩右邊的“丟”也可以……第一筆打撇。

「銩」思源字體及秋空黑體只有楷化字圖。

## 另外
- 可統一：
龹 - 𠔉
昷 - 𥁕

- 「示」（U+793B）可考慮使用「⺬」（U+2EAC）字圖。

**Comment by SCLu17** [comment]
「俁」「俣」不宜統一，「俣」是日文國字（また (mata)，「分岔位」義，又用於人名地名），與「俁」字不同音義，只不過大陸「俁」字新字形作「俣」形。

**Comment by GuiWonder** [comment]
> 「俁」「俣」不宜統一，「俣」是日文國字（また (mata)，「分岔位」義，又用於人名地名），與「俁」字不同音義，只不過大陸「俁」字新字形作「俣」形。

已取消「俁」「俣」的統一，感謝反饋。
