### ISSUE TITLE
About glyphs of 呆,保...

### ISSUE THREAD

**Issue by ghost** [GuiWonder/SourceHanToClassic#36]
There is difference between glyph of 呆,保,堡... compared to I.Ming:
![IMG_20230211_033150](https://user-images.githubusercontent.com/100918126/218192667-b368b40d-0cb6-4dbd-b85c-91e0e3bf9f7f.jpg)
In I.Ming:
![IMG_20230211_033407](https://user-images.githubusercontent.com/100918126/218192725-ad5d53ad-d2bf-4bb8-89f0-2d3f296b1375.jpg)

Hope you will check.

**Comment by Scratchbin** [comment]
但是思源原版好像没这个

**Comment by leejimmy90** [comment]
But Source Han Sans Taiwan has (思源黑體 TW). Characters likes 殺 are based on Taiwan version.

**Comment by Scratchbin** [comment]
那就是我疏忽了（）

**Comment by GuiWonder** [comment]
感谢反馈。`呆`字下方作`八`只有 TW 版的个别字图可用，为了部件统一这里就选择下方为`木`的字图。另外下方作`八`的写法多出现在楷体中，包括《康熙字典》在内的常见印刷体中下方写作`木`非常常见。  
![2023-2-11_14-1-6](https://user-images.githubusercontent.com/55447192/218245737-365dc84a-a0a2-4d3e-9ff9-0447eae0a449.png)
![2023-2-11_14-53-54](https://user-images.githubusercontent.com/55447192/218245749-aa7a5fd0-e0c7-48a0-a96e-a7c9ac52593c.png)
