### ISSUE TITLE
关于VF字体的兼容性问题

### ISSUE THREAD

**Issue by ryanlo713** [GuiWonder/SourceHanToClassic#37]
在比较古早开发的程式中只显示出一个字重，且默认为 EL，且只供选择 EL

![image](https://user-images.githubusercontent.com/12672523/221359400-b902beaa-3ff4-433b-8c8f-54475670fd0d.png)

可以像 Noto 字体（我装的都是VF）那样提供所有预设实例吗

![image](https://user-images.githubusercontent.com/12672523/221359583-de379778-c77c-482b-b096-6335d954ebcd.png)

**Comment by GuiWonder** [comment]
与[思源黑體](https://github.com/adobe-fonts/source-han-sans)/[思源宋體](https://github.com/adobe-fonts/source-han-serif)相同，VF 字体在 Windows 很多环境下存在不兼容的情况。这可能是 Windows 系统的原因，思源还没有提供解决方法，可参考 [adobe-fonts/source-han-sans/issues/317](https://github.com/adobe-fonts/source-han-sans/issues/317)，感谢反馈。

**Comment by GuiWonder** [comment]
TTF 可变字体在 Windows 下只能显示一个默认字重 EL，很可能是因为 Windows 对字形较多的字体兼容性不好引起的。目前暂时解决方法是使用 [fonttools subset](https://github.com/fonttools/fonttools) 削减字体的字形数目。
