### ISSUE TITLE
标点并未完全居中及竖排显示问题

### ISSUE THREAD

**Issue by ChellyL** [GuiWonder/SourceHanToClassic#39]
字体横排时标点并没有完全居中，而是偏左，见与全字库宋体的对比，可以改为完全居中吗？(图有点大，我折叠了)

<details><summary>标点居中问题</summary>

+ 尚古:
![screenshot_2023_03_19T17_09_45+0800](https://user-images.githubusercontent.com/38887991/226165719-d7778d58-8552-433f-b485-197409ab2d9e.png)

+ 全字库宋：
![screenshot_2023_03_19T17_09_57+0800](https://user-images.githubusercontent.com/38887991/226165470-d16eb073-8475-49fc-8b85-4d2a7d644fb1.png)

</details>

----------

以及竖排时，冒号“：”并未随之竖排，而是按横排效果显示，如图对比，不知这是否能修正？

<details><summary>竖排冒号问题</summary>

+ 尚古：

![screenshot_2023_03_19T17_14_11+0800](https://user-images.githubusercontent.com/38887991/226165522-d378bb52-e72b-4ec3-bc04-d381758dfdee.png)

+ 全字库宋：
![screenshot_2023_03_19T17_14_33+0800](https://user-images.githubusercontent.com/38887991/226165540-c8ab6b37-1a84-4be5-ad5d-3ae376115da2.png)
</details>

**Comment by GuiWonder** [comment]
这个字体的标点与思源相同，并且继承了思源的很多特性。我测试时是正常的，发现你的文章第一段后面有个引号与问号重合问题全字库宋也是如此，可能与你的文字处理工具有关，可以尝试找一找有没有字符调整、字符压缩类似选项（软件为防止标点在行首的做出的处理）。
![TestP1](https://user-images.githubusercontent.com/55447192/226169747-95f491cf-aa1a-49bd-828c-725841d8a1ae.png)

竖排冒号被旋转 90 度问题在 1.013 版中做过修复，原因是与日文标点相混（日文冒号竖排旋转 90 度）导致的。您可以检查一下字体的版本是不是新版。希望能帮到你，感谢反馈。
![TestP2](https://user-images.githubusercontent.com/55447192/226169928-b85e8ded-8dd2-4c5d-96f4-b4de21e74ef6.png)

**Comment by ChellyL** [comment]
感谢回复~
已经下载了最新的1.013版，竖排冒号问题已解决！
而标点并未完全居中问题依旧，我猜是我设备问题，我传的图片是kindle pw5上的显示效果，它的系统对中文字体支持不够好，试过好几个开源字体，应当居中的标点都是靠左显示，也有标点重合的现象，换成手机测试发现标点的确居中，估计只能看亚马逊会不会修复了……
再次感谢~
