### ISSUE TITLE
弯引号字形没有统一

### ISSUE THREAD

**Issue by Scratchbin** [GuiWonder/SourceHanToClassic#4]
`“`、`”`、`‘`、`’`，其全宽或半宽没有统一。为拉丁文字等排版方便我认为应选半宽。

**Comment by GuiWonder** [comment]
已统一为思源中文版（简繁相同）的字形。 通过代码生成时可选择日文标点。

**Comment by Scratchbin** [comment]
不过我这里 Python 不能正常运行，显示*不兼容 32 位系统*：
![image](https://user-images.githubusercontent.com/29145652/183270591-974813ba-c9d5-4947-b1ae-f0bbe2776f20.png)

**Comment by GuiWonder** [comment]
可能是版本问题，工具附带的 [otfcc](https://github.com/caryll/otfcc) 是 64 位版的，可以[下载](https://github.com/caryll/otfcc/releases/latest) 32 位版的试试，替换掉 otfcc 目录下的 otfccbuild.exe 和 otfccdump.exe 两个文件。

**Comment by Scratchbin** [comment]
换上了，行了 （）

**Comment by Scratchbin** [comment]
但是出现了这个（
![image](https://user-images.githubusercontent.com/29145652/183273540-0b230aae-2834-4974-8fe2-ec2d8809707d.png)
可能与我 PC 贫瘠的 RAM (2GB) 有关。*otfccdump.exe* 卡了很久崩了然后就是上图的情况。

**Comment by GuiWonder** [comment]
字体很大，尤其宋体，最好使用 4GB 以上的 PC。
