### ISSUE TITLE
「望󠄀」於󠄀尙古明󠄁體及󠄁VF寫作斜󠄁月󠄁

### ISSUE THREAD

**Issue by haydenwong7bm** [GuiWonder/SourceHanToClassic#40]
<img width="404" alt="image" src="https://user-images.githubusercontent.com/51369959/230928186-0cadf9c0-e52c-44f3-a8ba-0ea9846c5711.png">
<img width="650" alt="image" src="https://user-images.githubusercontent.com/51369959/230928497-efcbd4c9-9a12-46b9-9c12-48f9346d7446.png">
似乎受󠄁秋空󠄀黑體影響。

**Comment by GuiWonder** [comment]
秋空󠄁黑體的「望」字最接近「校驗表」，明󠄁體及󠄁 VF 使用了下方作「𡈼」的字圖，其他則使用了秋空黑體的「望」字圖。  

![20230412112321](https://user-images.githubusercontent.com/55447192/231340638-a04d754a-2f3b-42c3-87d7-274b0c860141.png)
