### ISSUE TITLE
關於字型標準的疑問

### ISSUE THREAD

**Issue by starcollect** [GuiWonder/SourceHanToClassic#42]
在本字型專案中，部分字型已默認更改為傳承字型（如：「直」、「為」等），但近日在翻看《傳承字形推薦形體表》(1.04版)時，看到其規則中提到：

- “五、異體字之間，若構形明顯相異，但部份形體字理較薄弱，或另有原因，以
致不宜取該異體，則以灰底暗紅色標示，並以註釋說明。例如「么」宜作「幺」，「匆」宜作「怱」或「悤」，「裡」宜作「裏」等。”。

以「匆」為例，本字型中並未直接將「匆」的代碼點替換為「怱」或「悤」的字型，所以想了解一下您對於字型取捨的看法

**Comment by GuiWonder** [comment]
您好，我認爲在不影響使用的情況下應該優先使用舊字形，比如`兑-兌，值-値，緒-緖，教-敎`這幾組意思是完全相同的，沒有必要當成兩個字來用。而像`么-幺`這情況，雖然`么`是`幺`俗寫但么同時還是`麼`的簡化字，在簡體中文中`么-幺`是完全不同兩個字，這種就需要區分開來(而`麽-麼`就不需要)。本字型基本上也是這樣得。
