### ISSUE TITLE
字形需要修改

### ISSUE THREAD

**Issue by shishamao** [GuiWonder/SourceHanToClassic#43]
本專集字型（無後綴版本）存在一些不合理的地方，希望能修改一下。
1. 录（嚴重bug）
本專案字型錯誤將录與彔合併爲彔，然而實录與彔並不相同。
彔，僅有一層意思
①.雕刻木材。《廣韻．入聲．屋韻》:「彔，刻木也。」
录，則有兩層意義
①.彔的俗字
②.録的簡化字
也就是說彔是不能用作録的簡化字的。 #3 的觀點是錯誤的。

2. 奂（部件）
奂與奐被合併爲奐，這種做法並不合理。奂與奐外形差異較大，奂字没有任何新字形楷化的成份，奂字雖是奐俗字但也是奐的簡體，奂奐合併之後造成簡繁混亂。對於不熟悉繁體字的用戶來說，很容易出現閱讀障礙，造成閱讀效率下降。
3. 争（部件）
争與爭被合併爲爭，這種做法並不合理。⺈與爫同樣没有新舊字形之分，且争與爭外形差異較大，與奂奐相同。

4. 吳（部件）
吴與吳被合併爲吳，不合理。原因同上。
5. 䍃（部件）
簡繁䍃部件被合併，不合理。原因同上。

作爲普通人的角度上來看，以上問題給本字型帶來了嚴重的缺陷和閱讀障礙。希望能改正。

**Comment by Scratchbin** [comment]
若要，另作源规格分离版较合适；或者改用秋空黑体 MN/CL 或思源黑体/宋体 SC。

**Comment by Scratchbin** [comment]
大陆官方也妹把这些（黃、虛、沒）当成繁体啊。照这么说直接把简体当成繁体用得了，绷

**Comment by Scratchbin** [comment]
大陆官方也没把这些（爭、黃、虛、沒、戶等，皆被视为简繁同形）当成繁体啊。照这么说直接把繁体当成简体用得了，可还行

**Comment by lxgw** [comment]
这是 GB/T 2312-1980 附录索引中的「新旧字形对照表」，「吴/吳」「奂/奐」「争/爭」「录/彔」等均被视作新旧字形关系。
![image](https://user-images.githubusercontent.com/51902309/236826868-0823255d-3a14-4323-b59b-cc7bd59759bd.png)

**Comment by Scratchbin** [comment]
> 奂争吴的繁體不是奐爭吳？你可以査詢一下類似「簡繁字典」、「簡繁對照表」以及其他的簡繁資料，無論大陸還是臺灣，都有明確收錄奐爭吳的簡體是奂争吴，奂争吴的繁體是奐爭吳。 這幾個字在字形上差異較大且有簡繁之分，被做成相同字形後，無法區分簡繁，造成簡繁混亂。如果喜歡繁體字形，完全可以通過輸入法等途徑來得到對應的漢字來使用繁體字形。如果從字體層面把兩種字形做成一種，使用者只能被強制使用繁體字形，而無法使用簡體字形。您可以參考一下其他舊字形字體（如原樣黑體）都沒有把這幾個字形差別較大且有簡繁之分的字形做成一種。

然而：“青”在编码上被分为“靑”和“青”，但**“情”没有按照这个差异分别编码**。别说你想让 Unicode 将“情”的差异字形到 **BMP 外**然后无意义地增加那个汉字占用的空间。

“奂”、“奐”应该是在判断的模糊地带里：“人”、“穴”、“廾”，“穴”省作“冖”可能并无不可，港台以“奐”为正，但**“奂”、“奐”被大陆视为字形差异**。

**“吴”“吳”、“争”“爭”同样被大陆视为字形差异**；而且既然是**传承字形**，除非是**源规格分离**以便分辨**不同字符**，否则将“吳”的“夨”讹作“天”、将“爭”的“爪”讹作“⺈”就是不妥。

你想这么干用原版思源或者秋空黑体（我甚至都能忍受在简体中使用这种源规格分离的传承字形字体两年多）不就行了？*这种过于片面、二极化的行为多少有点太极端了。*

**Comment by GuiWonder** [comment]
這些字在字的含義上是完全相同的，對於舊字形愛好者來說，統一成舊字形應是最佳選擇。
本項目已提供不帶任何合倂字的版本，您也可以使用這一版本。如果有特殊需求也可以通過本項目源代碼進行構建。感謝反饋與支持。

**Comment by garfieldLSY** [comment]
“謳”的“區”構件没有作“匸”，但是這一點比較容易解决。我用Font Creator嘗試了一下取思源宋體HK的“區”和思源宋體KR的“言”，發現即使是字重最重的Heavy也能近乎完美的契合，衹是“區”的首筆横與“言”的首筆横有細微的重疊（當然如果把字縮小了就看不大出來了）。

**Comment by SyaoranHinata** [comment]
抱歉現在才看到這討論，在下希望說一點個人意見。當然，在下尊重項目主人的決定，只是說一說愚見以供參考。

在字理上，「彔/录」、「奐/奂」、「爭/争」、「吳/吴」、「⿱𱼀缶/⿱爫缶」合併是完全合理的，它們的確是同一個字的不同寫法，前者是傳承字形，或稱舊字形，後者是所謂新字形。

至於樓主聲稱它們並沒有繁簡及新舊字形關係，乍看好像擧出一些論說，但請恕在下直言，竊以爲是有點偷換概念的。樓主的論述手法，就是聲稱某字形在按某一份規範文件裏是用作此形音義，而另一個字形則不如此，或者某一份規範文件沒有說它的某某規範就要作某，它們沒有新舊字形之分等等。但是事實上，這些不同字形的異體字關係，有多部權威字典可證。而它們之間的分別，的確是所謂新舊字形的分別。樓主所引的某一份規範文件沒說，就只是那份文件的疏失或未盡全面而已。

在下不是要苛責文件的編者，漢字是一套龐大的符號，再殫思竭慮也難以包山包海。然而樓主立論時，死抱未盡全面的文件，忽視眾多字書的說法、其他學者的硏究，如此劃地爲牢，然後聲稱這些在某文件以外的確實情況是項目主人犯了「嚴重的缺陷」，在治學態度來說並不可取。

這套字型的目標，也是面對需求傳承字形（或稱舊字形）的使用者。而樓主的取態，顯然有悖於眾多傳承字形使用者的需求，他大可以選用其他符合他願望的字型，或依開源規定自行改造，而不宜這樣要求項目主人，摧毀一眾本來符合傳承字形使用者的需求的好字型。希望項目主人能堅持初心，維持把「彔/录」、「奐/奂」、「爭/争」、「吳/吴」、「⿱𱼀缶/⿱爫缶」等都統一作傳承字形，感謝！

在下愚莽，發言如有任何失禮，還望海涵！

**Comment by GuiWonder** [comment]
謝謝指點！

**Comment by SyaoranHinata** [comment]
@shishamao 我這身份是個人發言，我上方也說明「在下希望說一點個人意見」。而一點明體由一點字坊維護，雖然我是其中一員，但不等於字坊的一切。敬希閣下好好理解在下的說話。

而我的發言，一是基於事實，尤其是閣下內容中一些事實錯誤，二是基於字型本身的特色或定位。《檢校表》也是從合不從分的。至於一點明體的做法，當然有其原因，但不見得每套字型都會跟一點明體一模一樣，一點明體或一點字坊也沒有要宣揚從分的意思。只是若要說一點明體方面的，就請移玉步，感謝！
