### ISSUE TITLE
「冕」使用錯誤字圖

### ISSUE THREAD

**Issue by haydenwong7bm** [GuiWonder/SourceHanToClassic#44]
<img width="200" alt="image" src="https://github.com/GuiWonder/SourceHanToClassic/assets/51369959/7ecde1c1-593b-4717-92cd-1ff88a172119">
<br>
<img width="500" alt="image" src="https://github.com/GuiWonder/SourceHanToClassic/assets/51369959/c8bb65f6-898a-4b34-9dff-438dddca0ec3">

**Comment by GuiWonder** [comment]
感謝！
