### ISSUE TITLE
「衆」下

### ISSUE THREAD

**Issue by ywxt** [GuiWonder/SourceHanToClassic#47]
依
![傳承字形部件校檢表](https://github.com/GuiWonder/SourceHanToClassic/assets/25864091/cb3be314-c54d-45bd-8eab-1dab6f48bbea)

「衆」下是否應作「眾」下？

**Comment by GuiWonder** [comment]
非常抱歉，「衆」字在思源中沒有下方作「人亻人」的字圖，所以沒得選了。

**Comment by ywxt** [comment]
理解理解
