### ISSUE TITLE
「拐」字處理問題

### ISSUE THREAD

**Issue by SCLu17** [GuiWonder/SourceHanToClassic#48]
Unicode「拐」(U+62D0) 字已統一，現時由於KR字圖用「另」形，導致TC及JP版未符各地慣用形，希望於下個版本作區分。

「叧」見於「枴」、「拐」、「箉」等，或作「𠮠」，或俗作「另」（見《傳承字形部件檢校表》99 (98)頁）。HK, TW, JP用「叧」形，CN, KR用「另」形。

按：Unicode「枴／柺」與「別／别」字則不統一，個人認為可以於各版本中維持分離。「箉」思源只有CN及JP圖，沒有從「叧」(TW指引)者，而「叧」「𠮠」皆通，個人認為毋須特別作處理。

**Comment by SCLu17** [comment]
一、此issue是基於日港臺慣用字形與專案TC, JP版有出入而開設。旣然TC/JP等版本的本意乃兼容地區寫法，「拐」字現時不符，値得關注。另外，「另」「叧」為別字，見各大字典口部２畫，並非單純書寫之異。

二、各項問題的迫切性，我相信GuiWonder等項目負責人能夠自行衡量。本issue討論範圍應限至「拐」字及「叧」部件。

**Comment by GuiWonder** [comment]
由於時間與精力有限，爭議話題就先暫時不處理了，非常抱歉。
