### ISSUE TITLE
奂䍃黄虚奥粤聖 未统一为旧字形

### ISSUE THREAD

**Issue by Scratchbin** [GuiWonder/SourceHanToClassic#5]
奂（奐）
䍃（部件）
黄（黃）
虚（虛）
奥（奧）
粤（粵）
聖（下部应作“𡈼”）

**Comment by GuiWonder** [comment]
找到可更新字形 奂㛟唤换涣焕痪摇遥謡瑶黄横奥粤虚嘘戯䔄熎䬙蘨蘣蘳嫹擙鐭聖，感谢！

**Comment by GuiWonder** [comment]
已更新字形 奂㛟唤换涣焕痪摇遥謡瑶黄横奥粤虚嘘戯䔄熎䬙蘨蘣蘳嫹擙鐭聖。
