### ISSUE TITLE
尙古明體1.018版本存在的問題一覽。

### ISSUE THREAD

**Issue by DevoteToStudy** [GuiWonder/SourceHanToClassic#59]
- [ ] 1、明體中“帰“字的右上角未出頭；
- [x] 2、⻌未合併爲⻍；
- [x] 3、⻎未合併爲⻍；
- [x] 4、“昌“及帶有“昌“的漢字的“昌“底部未从“曰“；
- [x] 5、明體中“望“的“亡“字似乎不是傳承字形，且“亡“字右邊的部件明體與黑體不一致；
- [x] 6、“辜“的“辛“部件首筆應爲橫（建議修正後檢查一下其他帶有“辛“部件的漢字是否寫對）；
- [x] 7、“智“字从“曰“不从“日“；
- [x] 8、 “識“字从“戠“，“戠“从“音“，“音“上邊爲橫，下邊爲“曰“（“意“也从“音“，也有同樣的錯誤。建議修正後檢查一下其他从“戠“、从“音）的漢字是否有同樣的錯誤）。；

![更正字圖](https://github.com/GuiWonder/SourceHanToClassic/assets/154590102/5e7d72d5-6d6e-4b30-af91-12406be4d8fe)

**Comment by Scratchbin** [comment]
> 2、⻌未合併爲⻍；
> 3、⻎未合併爲⻍；

兄啊都部首区了还要合并？（出于展示等原因。）

> 4、“昌“及帶有“昌“的漢字的“昌“底部未从“曰“；
> …
> 7、“智“字从“曰“不从“日“；
> 8、 “識“字从“戠“，“戠“从“音“，“音“上邊爲橫，下邊爲“曰“（“意“也从“音“，也有同樣的錯誤。建議修正後檢查一下其他从“戠“、从“音）的漢字是否有同樣的錯誤）。；

确立日-曰对立的话，可能不是不行；但出于统一（不是合并）及部分美观原因，感觉要么在一定范围内都分明对立要么“曰”非独字非左右结构状况下统成宽“日”形。

**Comment by DevoteToStudy** [comment]
@shishamao 
> 我認為這樣並無不妥。個人不喜歡帶缺口的「日」，尤其是黑體，實在是影響美觀。另外舊字形的傳統寫法有很多種，不能因為和某標準不一樣就稱之爲「錯誤」。

@Scratchbin 
> 确立日-曰对立的话，可能不是不行；但出于统一（不是合并）及部分美观原因，感觉要么在一定范围内都分明对立要么“曰”非独字非左右结构状况下统成宽“日”形。

        如果單單從講究傳承字形的美觀程度上——不講究字理——來說，你們的觀點言之鑿鑿，我無法反駁。但是如果要推究字理的話，你的觀點恕我不敢苟同。因爲“音“的本意是“聲“，《說文解字》曰：“音，聲也。生於心，有節於外，謂之音。宮商角徵羽，聲；絲竹金石匏土革木，音也。从言含一。“也就是說，“音“的本義是“人發出的聲音“，當然從“曰“（意思爲“說“）而不從“日“（意思爲“太陽“），[《康熙字典・音部》](https://www.kangxizidian.com/search/index.php?stype=Radical&sword=%E9%9F%B3&detail=n)爲證。

        私以爲傳承字形應當並重字的美感以及字理，不偏袒任何一方，纔能眞正展現傳承字形之美。

        當然正如@shishamao所言的：

> 舊字形的傳統寫法有很多種，不能因為和某標準不一樣就稱之爲「錯誤」。

       竊以爲舊字形的傳統寫法確實有很多種，但是不同的寫法都遵從著同一箇原則性問題——字理。在遵從字理的前提下，纔可以以雕刻者的審美標準來選擇不同的寫法。這樣的例子很多，如《康熙字典》中的“艹“是中間斷開的，而武英殿本的書籍中的“艹“是連起來的。總之就一句話：傳承字形的寫法的確很多，但是不管是哪一種寫法，都應該依從同一字理。

        謹呈拙見，貽笑大方。

**Comment by DevoteToStudy** [comment]
@Scratchbin 

> 兄啊都部首区了还要合并？（出于展示等原因。）
甚麼意思？你可以說的詳細一點嗎？

**Comment by Scratchbin** [comment]
> @Scratchbin 
> 
> > 兄啊都部首区了还要合并？（出于展示等原因。）
> 
> 甚麼意思？你可以說的詳細一點嗎？

如果展示某部首的不同写法，那么存有不同写法的部首 *字符*（“字元”）会因为在使用的字体中被合并的状况而呈同形。部首区基本并不用于日常交流。故不敢苟同。

**Comment by DevoteToStudy** [comment]
> > @Scratchbin
> > > 兄啊都部首区了还要合并？（出于展示等原因。）
> > 
> > 
> > 甚麼意思？你可以說的詳細一點嗎？
> 
> 如果展示某部首的不同写法，那么存有不同写法的部首 _字符_（“字元”）会因为在使用的字体中被合并的状况而呈同形。部首区基本并不用于日常交流。故不敢苟同。

確實，但是如果不合併，“尙古明體“還會是一箇比較純粹的“舊字形“字體嗎？“尙古明體“設計的初衷不就是要“基於思源“設計“傳承字形（舊字形）字體“嗎？不合併豈不與該初衷背道而馳了？

**Comment by Scratchbin** [comment]
> 確實，但是如果不合併，“尙古明體“還會是一箇比較純粹的“舊字形“字體嗎？“尙古明體“設計的初衷不就是要“基於思源“設計“傳承字形（舊字形）字體“嗎？不合併豈不與該初衷背道而馳了？

**死  循  环**

**Comment by Scratchbin** [comment]
> 如果單單從講究傳承字形的美觀程度上……

我已说：

> 要么在一定范围内都分明对立要么“曰”非独字非左右结构状况下统成宽“日”形

“一定范围”指在足够常用的字符范围内。

“非独字非左右结构状况下统成宽‘日’形”指：
如果“曰”作独体字或左右结构部件，留“曰”形；如果作其他结构部件，作较宽的“日”形以与“日”区分。这种区分可以保留识别“曰”的余地（但上下结构例外）。这种做法妥协于一些美观观点。

如果那同时存在能对立/分别上述两种不同做法的方式，那比较好；不过“工程量”（？）是个问题。

**Comment by DevoteToStudy** [comment]
> 帶缺口的「日」是「曰」？？即便是篆書都沒有這種規定，更不用說《康熙字典》之類的字書。這種為了區別而製造出來的區別，除了把字變醜毫無意義。建議都不要缺口。

“日“是“日“，“曰“是“曰“，帶缺口的“日“還是“日“，不是“曰“。還有，“日“與“曰“在《說文解字》的寫法中大相徑庭，“日“與“曰“估計是漢字隸變後形體變得相似。爲了區分二者，不致混淆，古代工匠在刻書時，將“日“中間的橫連到頭，而“曰“不連。這種區別幷不是現代人造的，是古已有之的，《康熙字典》爲證：[日部](https://www.kangxizidian.com/kxbushou/%E6%97%A5)，[曰部](https://www.kangxizidian.com/kxbushou/%E6%9B%B0)。

**Comment by Scratchbin** [comment]
> 閣下是只看了「曰」部嗎？《康熙字典》中「日曰目有」等字的中間橫都是不連到頭的，「日」和「曰」根本就不是用中間橫來區分的。

好像也就限于康熙字典等“宋体但横末连接与否类似或同楷书”的字体特性了

**Comment by DevoteToStudy** [comment]
@shishamao @Scratchbin 
𡂿，對不起，我確實看錯了。但是，尙古明體與黑體中“日“與“曰“的寫法確實不一，從“曰“不從“日“的“書“和“會“下半邊都沒有出頭。爲甚麼“音“、“識“等從“曰“的字要搞特殊？

**Comment by GuiWonder** [comment]
仔細査詢了一下「辶」字使用情況，基本使用的都是辶(U+8FB6)， 這個字位於中日韓統一表意字基本區。而「⻌⻍⻎」(U+2ECC, U+2ECD, U+2ECE)這三個字位於中日韓漢字部首補充區，一般用於指定某個字形而使用的。這三個字的存在，可能就是爲了對比不同地區的字形差異。

關於「日」和「曰」的區別。從篆體的字形上看，兩個字的中橫是對稱的，都不是在一側留缺口。在《康熙字典》之類的刻本中不論是「日」還是「曰」，大都帶有「缺口」，唯一的區別是「日」瘦長「曰」寬扁。在很多鉛字印刷中，不論是「日」部件還是「曰」部件，基本都沒有「缺口」，只有「曰」單字帶有「缺口」。單獨「曰」字帶「缺口」可能是因爲「曰」字字身較寬，爲了美觀而設計的。

感謝指敎，下次改一下「書」的字形，其他字形統一一下。

**Comment by DevoteToStudy** [comment]
> 仔細査詢了一下「辶」字使用情況，基本使用的都是辶(U+8FB6)， 這個字位於中日韓統一表意字基本區。而「⻌⻍⻎」(U+2ECC, U+2ECD, U+2ECE)這三個字位於中日韓漢字部首補充區，一般用於指定某個字形而使用的。這三個字的存在，可能就是爲了對比不同地區的字形差異。
> 
> 關於「日」和「曰」的區別。從篆體的字形上看，兩個字的中橫是對稱的，都不是在一側留缺口。在《康熙字典》之類的刻本中不論是「日」還是「曰」，大都帶有「缺口」，唯一的區別是「日」瘦長「曰」寬扁。在很多鉛字印刷中，不論是「日」部件還是「曰」部件，基本都沒有「缺口」，只有「曰」單字帶有「缺口」。單獨「曰」字帶「缺口」可能是因爲「曰」字字身較寬，爲了美觀而設計的。
> 
> 感謝指敎，下次改一下「書」的字形，其他字形統一一下。

好的，辛苦您了！
