### ISSUE TITLE
「華」部件不統一，建議統一爲中國大陸字圖。

### ISSUE THREAD

**Issue by DevoteToStudy** [GuiWonder/SourceHanToClassic#60]
對於「華」字，顯而易見，尙古字體採用了中國大陸字圖——即最下邊的橫要長於第三道橫。然而，在尙古字體中，有些有「華」字並未遵從這種寫法，建議統一一下。

- [ ] 1、不論是明體還是黑體，㠏（U+380F）的「華」部件正確，但是偏旁部首不是舊字形。
- [ ] 2、不論是明體還是黑體，「𦠜（U+2681C）」「𨅯（U+2816F）」是臺標醜字，不是舊字形。圖中用「∅」標註。
- [ ] 3、明體中，「嬅（U+5B05）」「澕（U+6F95）」「曄（U+66C4）」「樺（U+6A3A）」「燁（U+71C1）」「皣（U+76A3）」「瞱（U+77B1）」「譁（U+8B41）」「鏵（U+93F5）」「韡（U+97E1）」「驊（U+9A4A）」「鷨（U+9DE8）」的「華」部件最下邊的橫比第三道橫短，與單獨的「華」字不統一。其中，「譁（U+8B41）」中的「華」部件「艹」下邊的部分疑似使用了臺標醜字。
- [ ] 4、黑體中，「燁（U+71C1）」「皣（U+76A3）」「驊（U+9A4A）」的「華」部件最下邊的橫比第三道橫短，與單獨的「華」字不統一。其中，「譁（U+8B41）」中的「華」部件「艹」下邊的部分疑似使用了臺標醜字。

望採納，之所以指出字型中的問題是因爲樓主希望在該字型日趨完善的道路上盡自己的綿薄之力，絕無刁難挖苦之意！

![華](https://github.com/GuiWonder/SourceHanToClassic/assets/154590102/0db39870-95c3-4b60-b0c6-b471c9b647ba)

**Comment by DevoteToStudy** [comment]
> 我認為「華」字的末橫不應該指定那個橫長那個橫短，而是應該根據漢字的結構變化。比如「嬅」、「燁」字，為了避讓左側的捺筆，所以末橫會短一些；如果強行讓末橫長，字會變的**很難看很難看**。當前使用的日韓字形幾乎和《康熙字典》一致，建議不要亂改。

我不懂，你說的「字會變的**很難看很難看**」的「**很難看很難看**」體現在何處？

**Comment by DevoteToStudy** [comment]
> 不懂就不要亂講。喜歡大陸字形就用大陸字體，也可使用標準嚴格又符合字理的台標字體，舊字形不適合你。

你不要一棍子把人打死行嗎？首先，你說我「不懂」就「亂講」，你且看圖中的維基百科頁面中我劃出來的藍綫部分在去思考到底誰纔是眞正的「不懂」，誰纔是眞正的「亂講」。
![Screenshot 2024-01-05 at 21-43-51 威鋒數位 - 维基百科，自由的百科全书](https://github.com/GuiWonder/SourceHanToClassic/assets/154590102/de98f44d-6d50-48c5-8528-22bf7443eabc)
我之所以認爲「華」部件應該統一爲中國大陸字體的原因不是你所想得我「喜歡大陸字形就用大陸字體」，我之所以下這一箇結論原因如下：

1. 我查了維基百科，那些維基人是這麼說的（如上圖藍綫標記處所示），我也看了[《康熙字典》的「華」字頭](https://www.kangxizidian.com/kxhans/%E8%8F%AF)證實了他們說的是正確的，同時中國大陸字形的「華」符合這一標準，所以我纔建議改爲大陸字形；
2.  傳承字形界的權威[「I.Ming」](https://github.com/ichitenfont/I.Ming)雖然在「華」部件之中採用了末筆橫短於第三筆橫的造型，但是不管是什麼字——衹要I.Ming收錄了——凡有「華」部件者，「華」均爲此形。無獨有偶，以舊字形設計爲主的3.21版細明體（MingLiU），在這一方面，與I.Ming類似，凡是帶有「華」部件的字的「華」也基本採取了同一種寫法（「曅」與「𩻮」字例外）。這已經說明了我們已經有了統一字的單獨寫法以及部件寫法的能力和意識了。
![I Ming](https://github.com/GuiWonder/SourceHanToClassic/assets/154590102/6ceee929-d926-4008-ae88-5fa370efddcc)
![MingLiU3 21](https://github.com/GuiWonder/SourceHanToClassic/assets/154590102/dc11f46f-184c-40c2-9dea-72ec5935a811)
《康熙字典》裏邊則不然，估計是由於技術的限制——畢竟當時印刷形式是活字或者是雕版印刷罷——那時可能無法做到部件與獨體字統一罷，也許是當時雕刻家沒有這箇意識，凡是帶有「華」部件部件的字與「華」字基本不一樣：但那是幾百年前的事了，我們現在既然有這種技術以及意識了，緣何不統一呢？

以上就是我建議選擇中國大陸的「華」以及要求字與部件形體統一的眞正原因，不是閣下想得那樣「喜歡大陸字形」，而是經過了查資料考證并結合尙古字體的特點分析之後得出的結論，絕非無稽之談。不過還請閣下多多指敎。

無由會晤，不任區區嚮往之至。

**Comment by DevoteToStudy** [comment]
> 說誰素質低了？ 你這種自以為是胡說八道的人就素質高了！要點臉好不好？回去多讀幾年書，先學會怎麼做人吧。

你有充分的理由證明我在自以爲是、胡說八道嗎？算了，不想和你計較，不與你繼續辯論了，因爲我不想在這箇高雅的話題之下發起引戰。這件事就就這樣搪塞過去罷！但是我有一箇要求：以後凡是我發起的issue討論串不歡迎你的任何回覆！

從此，再見！𡂿，不，是再也不見！

**Comment by DevoteToStudy** [comment]
> 就事論事你為什麼要針對我？我為什麼就不能發言了？GitHub 是你家的？

行行行，我說「對不起」行了罷！如果你確實覺得我這麼做侵犯了你「至高無上」的「自由」與「人權」的話，就悉聽尊便罷！

但是我也求求你放過我罷！我來這裏是研究傳承字形的，不是跟你就一點雞毛蒜皮的曱甴事吵架的。求你放過我罷，我不想再跟你進行那些毫無意義的「辯論」了！我錯了！饒了我罷！ㄅ託！

**Comment by GuiWonder** [comment]
話題跑遠了吧，怎麼「人權」這種別詞都出來了？
