### ISSUE TITLE
「区」字與其他「区」部件漢字不統一

### ISSUE THREAD

**Issue by shishamao** [GuiWonder/SourceHanToClassic#63]
如圖，「区」字與其他「区」部件漢字不統一。另外，明體中「驱」字的「区」左上角存在BUG。
![66532](https://github.com/GuiWonder/SourceHanToClassic/assets/112676634/40ed8d8d-c882-4a0f-b031-3c4d8f31a784)

**Comment by GuiWonder** [comment]
感謝指正。
