### ISSUE TITLE
建議使用我的字形編輯改進字型

### ISSUE THREAD

**Issue by Marcus98T** [GuiWonder/SourceHanToClassic#64]
https://github.com/Marcus98T/SHS-UFO-Edits/tree/main/Sources/Old-Traditional

我知道您最近新增了您自己修改的字形擴展了尚古字型的字元集，但我有質量更好的 UFO 格式字形原始檔。抱歉，自述文件只有英文版。

[這是我的 PDF 格式的字形預覽。](https://github.com/Marcus98T/SHS-UFO-Edits/blob/main/Sources/Old-Traditional/Sans/Preview/WIPSHDC-Old-Traditional-Sans-Regular.pdf)

**Comment by GuiWonder** [comment]
感謝提供資源。

**Comment by Marcus98T** [comment]
我會偶爾更新我的儲存庫，所以敬請留意。

**Comment by Marcus98T** [comment]
我猜您的軟體 FontCreator Professional 可以導入和匯出 UFO 格式，另外，您可以以 UFO 格式匯出您的字形編輯，這樣我就可以改進它們的品質。

https://www.high-logic.com/font-editor/fontcreator/features-and-benefits

另一方面，昭源字體系列具有 UFO 格式的來源，因為它是 Google Fonts 提交所必需的。即使它們的字形政策是新字形，但昭源黑體有一點 JP 式字形，您可以將它們的一些字形包含到您的字體中。
https://github.com/chiron-fonts/chiron-hei-hk-gf
https://github.com/chiron-fonts/chiron-sung-hk-gf

**Comment by GuiWonder** [comment]
確實可以透過軟體匯入或匯出 UFO 格式，不過這只是 Binary 與 Text 之間的改變。由於我一直基於思源黑體/思源宋體提供的 VF TTF 二次貝塞爾曲線繪製字圖的，這與您使用的三次貝塞爾曲線不同，而使用工具轉換得到的三次貝塞爾曲線質量非常糟糕（ #65 ）。要得到質量好的三次貝塞爾曲線，恐怕只能將字圖全部重繪。

**Comment by Marcus98T** [comment]
知道，那我將繼續參考您的字形來重新建立具有三次貝塞爾曲線的高品質版本。看來除了難做這件事之外別無選擇。

**Comment by ChiuMing-Neko** [comment]
根據我在#65 中的共用字形庫的提議，我近期考慮提前開放秋空󠄁明󠄁朝󠄁的github專案並提供三次貝塞爾曲線的源文件（pfa格式），即使沒有在2024年9月之前正式推出秋空󠄁明󠄁朝󠄁的打算。

而秋空󠄁黑體本身已經提供源文件，且似乎 @Marcus98T 已經將部分字形進行修改，所以這個本身就不是問題。不過黑體改作還是得讓步於明󠄁朝󠄁的進度，所以黑體暫時幫不了忙。

cc. @Marcus98T @GuiWonder
