### ISSUE TITLE
希望釋出新字圖的UFO或PFA源文件以方便後續改作

### ISSUE THREAD

**Issue by ChiuMing-Neko** [GuiWonder/SourceHanToClassic#65]
非常感謝本項目能增加許多印刷體筆形的字圖，不過由於工具限制想從已構建的文件逆向重構源文件實在是有些許困難，因此希望能開源這一部分文件以方便後續改作。

**Comment by ChiuMing-Neko** [comment]
已經逆向導出成功，感謝作者的辛苦勞動。

**Comment by GuiWonder** [comment]
逆向導出成功太好了。此字體是我直接修改的可變 ttf，未使用開源格式，要得到UFO，我也是需要逆向轉換的。

**Comment by ChiuMing-Neko** [comment]
> 逆向導出成功太好了。此字體是我直接修改的可變 ttf，未使用開源格式，要得到UFO，我也是需要逆向轉換的。

從可變OTF逆向導出的，不過個人發現筆畫方面確實有些許問題可能需要重繪成原版思源的三次貝塞爾曲線筆畫。雖然目前確實可以用且可以進行字重插值作業，但是為了後續作品改作我考慮在筆畫級別進行重繪。不過有了字形參考的話，基本上不用浪費時間進行字形微調也是好事。

**Comment by ChiuMing-Neko** [comment]
不過我認為出於避免重複勞動的考量，還有就是多人協作效率更好更能快速補全整個字庫。個人建議最好建立一個共同協作的repo放置那些新繪製的字圖，如果可以共用那麼就共用，而如有字形方面的取捨的話（譬如我一般是按いわゆる康煕字典体/活字印刷慣用字形/現代繁中地區印刷體字形造的）可以另外基於已有的字圖進行修改並一塊放置，這個絕對比起各自造字要來得高效許多，而且亦方便其他改作作品可以以比較少的精力進行後續改作。

可以參考[Marcus9T](https://github.com/Marcus98T/SHS-UFO-Edits)的方案，以三次貝塞爾曲線為基礎進行繪製，然後再生成其他格式。

**Comment by GuiWonder** [comment]
感謝您的建議，這的卻是一個非常好的方案。不過我缺乏這方面的技術，一直都是在ttf基礎上繪製字圖，對UFO格式很陌生。

**Comment by GuiWonder** [comment]
我嘗試了一下對轉換的三次曲線進行自動輪廓優化。只成功了一小部分，而且有些筆畫會出現變形。我已經把有問題的字圖全部移除（不過難免有遺漏）。優化后的三次曲線和思源原版比較接近。 
 
[Sans-VF.designspace.zip](https://github.com/GuiWonder/SourceHanToClassic/files/14001419/Sans-VF.designspace.zip)
[Serif-VF.designspace.zip](https://github.com/GuiWonder/SourceHanToClassic/files/14001421/Serif-VF.designspace.zip)

**Comment by GuiWonder** [comment]
[1.021版](https://github.com/GuiWonder/Shanggu/releases/tag/1.021)版的大部分字圖在三次曲線下重新繪製的，質量應該好一些。
