### ISSUE TITLE
我想按照您的构想，尚古黑体这两个字也应该是一个字型

### ISSUE THREAD

**Issue by hugh1927** [GuiWonder/SourceHanToClassic#66]
![S40110-11382570](https://github.com/GuiWonder/SourceHanToClassic/assets/61912504/15373651-7846-4f22-9084-0d35b2c64b34)
只是建议，感谢您的无私分享和长期维护

**Comment by GuiWonder** [comment]
感谢反馈。之前“鈃”、“銒”这两个字是相同的字形，后来根据 #34 的建议使用两种不同的字形。详情请阅读 #34 ，如果您有好的建议，可参与讨论，谢谢。

**Comment by hugh1927** [comment]
受教了😀辛苦

在 2024-01-10 18:21:27，GuiWonder ***@***.***> 写道：


感谢反馈。之前“鈃”、“銒”这两个字是相同的字形，后来根据 #34 的建议使用两种不同的字形。详情请阅读 #34 ，如果您有好的建议，可参与讨论，谢谢。
