### ISSUE TITLE
明體「韌」字基線

### ISSUE THREAD

**Issue by SCLu17** [GuiWonder/SourceHanToClassic#71]
![Screenshot from 2024-01-22 13-35-03](https://github.com/GuiWonder/SourceHanToClassic/assets/85668984/15de0986-97c4-4eb6-8359-2dc71e99a922)

如圖所示，明體「韌」字基線（橙）並非於底（紅），縱排時會與下個字重疊。
應該涉及所有明體版本 (OTF 與 TTF)，我看黑體沒有同樣問題。

**Comment by GuiWonder** [comment]
問題字形已被替換，可從 [Releases](https://github.com/GuiWonder/SourceHanToClassic/releases) 中重新下載。感謝反饋！
