### ISSUE TITLE
爲何Rounded沒有Bold字重

### ISSUE THREAD

**Issue by haydenwong7bm** [GuiWonder/SourceHanToClassic#72]
![Resource Han Rounded](https://github.com/GuiWonder/SourceHanToClassic/assets/51369959/8e7df1b6-fd70-4a92-813a-5b320a5a5f6d)
![Advocate Ancient](https://github.com/GuiWonder/SourceHanToClassic/assets/51369959/ac605422-43e4-4dd1-ab26-682ff9e694d3)

**Comment by GuiWonder** [comment]
現已添加缺失的 Bold，可從 [Releases](https://github.com/GuiWonder/SourceHanToClassic/releases) 中重新下載。感謝反饋！
