### ISSUE TITLE
异體字選擇器异常

### ISSUE THREAD

**Issue by garfieldLSY** [GuiWonder/SourceHanToClassic#75]
“謳”、“刻”等在Adobe-Japan1中衹有一個异體字字碼的字在更改字圖後均無法正常使用异體字選擇符，而在保留原字圖的基礎上另開字圖不會發生這個問題。
請問這個問題需要解决嗎？

**Comment by garfieldLSY** [comment]
那明白了，謝謝。

**Comment by GuiWonder** [comment]
改過的字由於字形與異體字選擇器不匹配，所以異體字選擇器都移除了。
