### ISSUE TITLE
Change the name in English

### ISSUE THREAD

**Issue by ghost** [GuiWonder/SourceHanToClassic#81]
- Agenda Items Addressed in this Issue: Change the font name in English.
- Agenda Items Not Addressed in This Issue: Names in Chinese, Korean, Japanese, Vietnamese, and other languages of the Chinese character culture.

---
The current, English-language name is Shanggu. It is derived from Mandarin Chinese.
Using a name derived from Mandarin Chinese in English (or in a language from a non-Kanji-speaking region, such as French or Spanish) causes the following problems:

- It is possible that Shanggu will be misunderstood as a font for Chinese and will be shunned (based on misunderstanding) by those looking for a font for Japanese or Korean.

---

For example, Adobe's Source Han Sans has an English name that is neither Pinyin nor Hepburnian romanization. Thus, by avoiding the adoption of Pinyin in the name of the font and "translating" it into English, one can avoid the misunderstanding that this font is only for Chinese.

**Comment by OnlyTrmp** [comment]
真是笑话，更纱黑体 Sarasa Gothic（日语）、源樣黑體 GenYoGothic（日语）、水木黑体 Mizuki Gothic（日语）…… 这些英文名使用日语罗马字没有问题，Shanggu 使用汉语拼音就不行了吗？这种双标真让人无语。你们人都这么不要脸吗？

What a joke! Sarasa Gothic (Japanese), GenYoGothic (Japanese), Mizuki Gothic (Japanese)... these English names use Japanese Romanization without any problem, but Shanggu can't use Chinese Pinyin? This double standard is truly speechless. Are you all so shameless?
