### ISSUE TITLE
"实"字错误

### ISSUE THREAD

**Issue by hingbong** [GuiWonder/SourceHanToClassic#9]
![图片](https://user-images.githubusercontent.com/26398240/186806274-bbe502a2-98d0-4565-892d-38970d6fc6be.png)
最新的转换出现这个情况
使用的是
```
sourcehantocl.py xxx.ttf xxx.ttf n 1 1 n 2
```
这个配置
下载路径
[Advocate-Ancient.zip](https://github.com/hingbong/YaHei-Build/releases/download/upstream-2.004-2.001-1.002-R-SourceHanToClassic-5eac145/Advocate-Ancient.zip)

**Comment by GuiWonder** [comment]
已做出修复，感谢反馈。

**Comment by GuiWonder** [comment]
你好，我在测试你的字体中，发现“夢儚喒嘬夢尠淲澂甍殺鎩摋蕞蠛馛”等没有被转换，应该是ttc2ttf使用了FontForge导致的。

**Comment by hingbong** [comment]
> 你好，我在测试你的字体中，发现“非夢儚喒嘬夢尠淲澂甍殺鎩摋蕞蠛馛”等没有被转换，应该是ttc2ttf使用了FontForge导致的。

感谢提醒，换了个工具，看起来是可以了
